# Build a docker image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/testautomation', '--cache-from', 'gcr.io/$PROJECT_ID/testautomation', '.' ]
# Push the docker image to container registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/testautomation']
# Execute the tests by invoking docker compose
- name: 'docker/compose:1.15.0'
  args: ['run', 'automation']
  env:
   - 'PROJECT_ID=$PROJECT_ID'
   - 'PROJECT_NAME=${_PROJ}'
   - 'RELEASE_NAME=${_RELEASE}'
   - 'TESTSET_NAME=${_TESTSET}'